---
- hosts: "*"
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_ssh_pass: "{{ ssh_pass }}"
    ansible_become_pass: "{{ ssh_pass }}"
  vars_prompt:
    - name: "ssh_pass"
      prompt: "ssh password?"
  tasks:
    - shell: |
        apt-get install ntp -y
        ntpdate -s ntp.ubuntu.com
        date
    # - copy:
    #     src: "{{ file }}"
    #     dest: /tmp/
    # - shell: |
    #     cd /var/www/web
    #     mv /tmp/{{ file }} /var/www/web
    #     tar -vxf {{ file }}
...
# ex: ansible-playbook aws.yml -i users.cfg -vvv
